[build]
  command = "remix vite:build"
  publish = "dist/client"
  functions = "dist/functions"

[dev]
  command = "remix vite:dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
